### ISSUE TITLE
DevSandbox context should not use default namespace

### ISSUE THREAD

**Issue by markmc** [redhat-developer/podman-desktop-sandbox-ext#86] opened 2023-06-23 11:41 UTC
After adding a new dev sandbox in Podman Desktop, it took me some time to realize it wasn't working because the created context had no namespace specified (so the default namespace was used) and not the devsandbox namespace that had been allocated to me

If I try running the `oc login` command myself, I do get a context with the correct namespace

**Comment by slemeur** [comment] 2023-06-23 13:48
duplicate of https://github.com/containers/podman-desktop/issues/2562

**Comment by slemeur** [comment] 2023-06-23 13:49
Thanks for your report @markmc !

**Comment by dgolovin** [comment] 2023-07-26 05:55
Closing as duplicate.

**Closed by dgolovin** 2023-07-26 05:55 UTC
Labels: bug
