### ISSUE TITLE
Sandbox extension crashes Podman Desktop

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/podman-desktop-sandbox-ext#104] opened 2024-05-16 20:50 UTC
Installing the sandbox extension from the catalog (v0.0.2) causes Podman Desktop to crash. After this you cannot restart Podman Desktop.

M1 MacBook with Sonoma 14.5.

[sandbox-failure.txt](https://github.com/redhat-developer/podman-desktop-sandbox-ext/files/15340895/sandbox-failure.txt)

**Comment by deboer-tim** [comment] 2024-05-16 23:51
If I run the published extension v0.0.2 using 1.10.2 or via `yarn watch`, Podman Desktop crashes.

If I clone the extension and do a `yarn build` locally, then copy `node_modules` over to .local/shared/containers/podman-desktop/plugins/ghcrioredhatdeveloperpodmandesktopsandboxext, it works both using 1.10.2 or via `yarn watch`.

Either the move to node 18 or dependency updates since v0.0.2 fixes this. Looks like the release workflow hasn't been updated to Node 18, but we should do that, release a v0.0.3, and get it in the catalog ASAP.

**Comment by jeffmaury** [comment] 2024-05-17 06:50
I do not reproduce by installing the extension from the catalog. Will check with yarn watch

**Comment by odockal** [comment] 2024-05-17 07:51
I cannot reproduce on Mac Mini M2 with Mac OS 14.5, podman desktop 1.10.2 + dev sandbox 0.0.2, tried installing from Extensions page (0.0.2) and with extensions pack.

**Comment by jeffmaury** [comment] 2024-05-17 14:22
Fixed by https://github.com/redhat-developer/podman-desktop-sandbox-ext/releases/tag/v0.0.3

**Closed by jeffmaury** 2024-05-17 14:22 UTC
